kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: devsecops-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000  # NodePort for web app
        hostPort: 30000
      - containerPort: 30090  # NodePort for Prometheus
        hostPort: 30090
      - containerPort: 30080  # NodePort for Grafana
        hostPort: 30080
