server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push  # Change `loki` if different in your cluster

scrape_configs:
  - job_name: falco
    static_configs:
      - targets:
          - localhost
        labels:
          job: falco
          __path__: /var/log/falco.log
