apiVersion: v1
kind: PersistentVolume
metadata:
  name: secure-upload-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/kind-storage"  # Folder will be created on your Mac
  persistentVolumeReclaimPolicy: Retain
