apiVersion: v1
kind: Service
metadata:
  name: secure-upload-server-service
spec:
  selector:
    app: secure-upload-server
  ports:
    - protocol: TCP
      port: 5000        # Expose port 5000 in service
      targetPort: 5000  # Forward to container port 5000
  type: ClusterIP      # Default type, no NodePort
