{
 "title": "Grafana_Queries_for_Falco",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "{app=\"falco\"} != \"Alert\" (logs)",
   "type": "logs",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "{app=\"falco\"} != \"Alert\""
    }
   ]
  },
  {
   "title": "Count Over Time {app=\"falco\"} != \"Alert\" (5m)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "count_over_time({app=\"falco\"} != \"Alert\" [5m])"
    }
   ]
  },
  {
   "title": "{app=\"falco\"} != \"TerminalShell\" (logs)",
   "type": "logs",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "{app=\"falco\"} != \"TerminalShell\""
    }
   ]
  },
  {
   "title": "Count Over Time {app=\"falco\"} (5m)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "count_over_time({app=\"falco\"} [5m])"
    }
   ]
  }
 ]
}